# Generated by Django 4.2.2 on 2023-07-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0009_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario'),
        ),
    ]
