# Generated by Django 4.2.2 on 2023-07-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0010_detalle_boleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(blank=True, max_length=15, verbose_name='Estado'),
        ),
    ]
